[package]
name = "lc3p2atest"
version = "0.2.0"
authors = ["cr0sh <ska827@snu.ac.kr>"]
edition = "2018"

[features]
default = ["parallel-test"]
parallel-test = ["rayon"]

[dependencies]
lc3-rs = "0.3"
rand = "0.6"
rayon = { version = "1.0", optional = true}
floating-duration = "0.1"
conv = "0.3"